namespace NativeHammer;

internal enum ManipulationMode_t
{
	MANIPULATION_MODE_INVALID = -1,
	MANIPULATION_MODE_SELECT,
	MANIPULATION_MODE_TRANSLATE,
	MANIPULATION_MODE_ROTATE,
	MANIPULATION_MODE_SCALE,
	MANIPULATION_MODE_PIVOT,
	MANIPULATION_MODE_COUNT,
}
