using System;

namespace NativeEngine
{
	internal enum ELightShadowMode
	{
		SHADOW_MODE_NONE = 0,
		SHADOW_MODE_FULLY_DYNAMIC_VARIANCE_SHADOWS = 1,
		SHADOW_MODE_VOLUMETEXTURE_SHADOWS = 2,
		SHADOW_MODE_DO_NOT_OVERRIDE = 3
	}
}
