
namespace NativeEngine
{
	internal enum RenderTextureDimension : sbyte
	{
		RENDER_TEXTURE_DIMENSION_INVALID = -1,
		RENDER_TEXTURE_DIMENSION_1D = 0,
		RENDER_TEXTURE_DIMENSION_2D,
		RENDER_TEXTURE_DIMENSION_2D_ARRAY,
		RENDER_TEXTURE_DIMENSION_3D,
		RENDER_TEXTURE_DIMENSION_CUBE,
		RENDER_TEXTURE_DIMENSION_CUBE_ARRAY,
		RENDER_TEXTURE_DIMENSION_BUFFER,

		RENDER_TEXTURE_DIMENSION_COUNT,
	}
}
