
namespace NativeEngine
{
	internal enum RenderShaderType
	{
		RENDER_SHADER_TYPE_INVALID = -1,
		RENDER_PIXEL_SHADER = 0,
		RENDER_VERTEX_SHADER,
		RENDER_GEOMETRY_SHADER,
		RENDER_HULL_SHADER,
		RENDER_DOMAIN_SHADER,
		RENDER_COMPUTE_SHADER,

		RENDER_SHADER_TYPE_COUNT,
	}
}
